# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
    ignore:
    # Ignore updates to Django package until LTS version
    - dependency-name: "django"
      versions: ["4.0.X", "4.1.X", "5.0.X", "5.1.X", "6.0.X", "6.1.X", "7.0.X", "7.1.X"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999

  # Interactive package.jsons, that will be simplified when https://github.com/dependabot/dependabot-core/issues/2178 is completed
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/algorithm-timer/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/big-number-calculator/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/bin-packing/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/box-rotation/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/box-translation/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/caesar-cipher/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/city-trip/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/cmy-mixer/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/colour-matcher/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/data-bias/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/data-visualisation/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/frequency-analysis/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/jpeg-compression/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/matrix-simplifier/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/packet-attack/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/password-guesser/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/python-interpreter/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/rgb-mixer/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/rsa-decryption/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/rsa-encryption/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/rsa-key-generator/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/scene-editor/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/sha2/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/sorting-algorithms/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/training-ground/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/unicode-binary/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/unicode-chars/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/interactives/viola-jones-face-detector/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
  - package-ecosystem: "npm"
    directory: "/csfieldguide/static/js/modules/fsa/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
