version: "3.8"

services:
    django:
        build:
            context: .
            dockerfile: ./infrastructure/local/django/Dockerfile
        image: cs_field_guide_local_django
        volumes:
            - ./csfieldguide/:/app/:z
        env_file:
            - ./infrastructure/local/django/.envs
            - ./infrastructure/local/postgres/.envs
        command: /start
        networks:
            - uccser-development-stack
            - backend
        labels:
            # General labels
            - "traefik.enable=true"
            - "traefik.docker.network=uccser-development-stack"
            - "traefik.http.services.cs-field-guide-django.loadbalancer.server.port=8000"
            # HTTPS
            - "traefik.http.routers.cs-field-guide-django.entryPoints=web-secure"
            - "traefik.http.routers.cs-field-guide-django.service=cs-field-guide-django"
            - "traefik.http.routers.cs-field-guide-django.rule=Host(`cs-field-guide.localhost`)"
            - "traefik.http.routers.cs-field-guide-django.tls=true"

    # Node server for creating static files
    node:
        build:
            context: .
            dockerfile: ./infrastructure/local/node/Dockerfile
        image: cs_field_guide_local_node
        volumes:
            # https://burnedikt.com/dockerized-node-development-and-mounting-node-volumes/#exclude-node_modules-from-the-mount
            - ./csfieldguide/package.json:/app/package.json:z
            - ./csfieldguide/package-lock.json:/app/package-lock.json:z
            - ./csfieldguide/gulpfile.js:/app/gulpfile.js:z
            - ./csfieldguide/static:/app/static:z
            - ./csfieldguide/build:/app/build:z
            - /app/static/js/modules/fsa
            - /app/static/interactives/algorithm-timer
            - /app/static/interactives/big-number-calculator
            - /app/static/interactives/bin-packing
            - /app/static/js/translation-rotation-interactives
            - /app/static/interactives/caesar-cipher
            - /app/static/interactives/city-trip
            - /app/static/interactives/cmy-mixer
            - /app/static/interactives/colour-matcher
            - /app/static/interactives/data-bias
            - /app/static/interactives/data-visualisation
            - /app/static/interactives/frequency-analysis
            - /app/static/interactives/jpeg-compression
            - /app/static/interactives/matrix-simplifier
            - /app/static/interactives/packet-attack
            - /app/static/interactives/password-guesser
            - /app/static/interactives/python-interpreter
            - /app/static/interactives/rgb-mixer
            - /app/static/interactives/rsa-decryption
            - /app/static/interactives/rsa-encryption
            - /app/static/interactives/rsa-key-generator
            - /app/static/interactives/scene-editor
            - /app/static/interactives/sha2
            - /app/static/interactives/shannon-experiment
            - /app/static/interactives/sorting-algorithms
            - /app/static/interactives/training-ground
            - /app/static/interactives/unicode-binary
            - /app/static/interactives/unicode-chars
            - /app/static/interactives/viola-jones-face-detector

        command: npm run dev
        networks:
            - backend

    puppeteer:
        image: buildkite/puppeteer:10.0.0
        volumes:
            - ./csfieldguide/make-interactive-thumbnails.js:/make-interactive-thumbnails.js:z
            - ./csfieldguide/staticfiles:/staticfiles:z
            - ./csfieldguide/build:/build:z
        profiles:
            - static-files
        networks:
            - backend

    postgres:
        image: postgres:13.8
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        env_file:
            - ./infrastructure/local/postgres/.envs
        networks:
            - backend

    docs:
        image: ghcr.io/uccser/local-docs-image:latest
        volumes:
            - ./docs:/docs:z
        networks:
            - uccser-development-stack
        labels:
            # General labels
            - "traefik.enable=true"
            - "traefik.http.services.cs-field-guide-docs.loadbalancer.server.port=7000"
            # HTTPS
            - "traefik.http.routers.cs-field-guide-docs.entryPoints=web-secure"
            - "traefik.http.routers.cs-field-guide-docs.service=cs-field-guide-docs"
            - "traefik.http.routers.cs-field-guide-docs.rule=Host(`docs.cs-field-guide.localhost`)"
            - "traefik.http.routers.cs-field-guide-docs.tls=true"

networks:
    backend:
        driver: bridge
    uccser-development-stack:
        external: true
