version: "3.8"

services:
    django:
        build:
            context: .
            dockerfile: ./infrastructure/local/django/Dockerfile
        image: cs_field_guide_local_django
        volumes:
            - ./csfieldguide/:/app/:z
        env_file:
            - ./infrastructure/local/django/.envs
            - ./infrastructure/local/postgres/.envs
        command: /start
        networks:
            - uccser-development-proxy
            - backend
        labels:
            # General labels
            - "traefik.enable=true"
            - "traefik.docker.network=uccser-development-proxy"
            - "traefik.http.services.cs-field-guide-django.loadbalancer.server.port=8000"
            # HTTPS
            - "traefik.http.routers.cs-field-guide-django.entryPoints=web-secure"
            - "traefik.http.routers.cs-field-guide-django.service=cs-field-guide-django"
            - "traefik.http.routers.cs-field-guide-django.rule=Host(`cs-field-guide.localhost`)"
            - "traefik.http.routers.cs-field-guide-django.tls=true"

    # Node server for creating static files
    node:
        build:
            context: .
            dockerfile: ./infrastructure/local/node/Dockerfile
        image: cs_field_guide_local_node
        volumes:
            # https://burnedikt.com/dockerized-node-development-and-mounting-node-volumes/#exclude-node_modules-from-the-mount
            - ./csfieldguide/package.json:/app/package.json:z
            - ./csfieldguide/package-lock.json:/app/package-lock.json:z
            - ./csfieldguide/gulpfile.js:/app/gulpfile.js:z
            - ./csfieldguide/static:/app/static:z
            - ./csfieldguide/build:/app/build:z
        command: npm run dev
        networks:
            - backend

    puppeteer:
        image: buildkite/puppeteer:10.0.0
        volumes:
            - ./csfieldguide/make-interactive-thumbnails.js:/make-interactive-thumbnails.js:z
            - ./csfieldguide/staticfiles:/staticfiles:z
            - ./csfieldguide/build:/build:z
        profiles:
            - static-files
        networks:
            - backend

    postgres:
        image: postgres:13.3
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        env_file:
            - ./infrastructure/local/postgres/.envs
        networks:
            - backend

    docs:
        image: ghcr.io/uccser/local-docs-image:latest
        volumes:
            - ./docs:/docs:z
        networks:
            - uccser-development-proxy
        labels:
            # General labels
            - "traefik.enable=true"
            - "traefik.http.services.cs-field-guide-docs.loadbalancer.server.port=7000"
            # HTTPS
            - "traefik.http.routers.cs-field-guide-docs.entryPoints=web-secure"
            - "traefik.http.routers.cs-field-guide-docs.service=cs-field-guide-docs"
            - "traefik.http.routers.cs-field-guide-docs.rule=Host(`docs.cs-field-guide.localhost`)"
            - "traefik.http.routers.cs-field-guide-docs.tls=true"

networks:
    backend:
        driver: bridge
    uccser-development-proxy:
        external: true
